kind: Deployment
apiVersion: apps/v1
metadata: 
         name: mydeployment
   spec:
        replica: 2
        selectors:
        matchLabels:
                    app: myspringbootapp
        template:
            metadata:
                     lables:
                            app:myspringboot
   spec:
        containers:
                  -name: containername
                  image: 
        imagepullpoilcy: Always
        ports:
          -containerport: 9099

          

